version: 2.1

jobs:
  hello-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, World!"
  deploy-to-render-production:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Deploy to Render production
          command: |
            if [ -z "$RENDER_API_KEY" ]; then
              echo "RENDER_API_KEY is not set. Configure it in your project or org context settings." && exit 1
            fi
            if [ -z "$RENDER_SERVICE_ID" ]; then
              echo "RENDER_SERVICE_ID is not set. Configure it in your project or org context settings." && exit 1
            fi
            curl -X POST \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -d '' \
              https://api.render.com/deploy/$RENDER_SERVICE_ID
workflows:
  hello-world-workflow:
    jobs:
      - hello-world-job
      - deploy-to-render-production:
          requires:
            - hello-world-job
