version: 2.1

jobs:
  hello-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, World!"
  deploy-to-render-production:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Deploy to Render production
          command: |
            # Example deployment command using curl to Render API
            curl -X POST \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -d '' \
              https://api.render.com/deploy/srv-REPLACE_WITH_SERVICE_ID
workflows:
  hello-world-workflow:
    jobs:
      - hello-world-job
      - deploy-to-render-production:
          requires:
            - hello-world-job
